### ISSUE TITLE
Add a dropdown to select marker source

### ISSUE THREAD

**Issue by hrishikeshpaul** [hubmapconsortium/ccf-asct-reporter#10]
## Current Behavior

**REVIEW**

> button/drop down for Marker source Gene (RNA), Protein (MxIF, CODEX) Protein (Flow cytometry) Excellent suggestion from Sanjay Jain (WUSTL)  in Zoom R07/30/2020 with Ellen Q when we were discussing ways to represent RNA-seq markers (genes) vs Protein names vs Flow cytometry derived +/-, high/low, bright/dim
Add another button similar to the “Cell Types” & “Biomarkers” which provides user the ability to select based on Gene, Protein, Flow Cytometry, All

Currently biomarkers have only once source, which is the data on the flattened tables.

## Improvements

Biomarkers can have multiple sources, 
- Gene (RNA)
- Protein  
- Flow cytometry
- All
- Lipids
- Metabolides

Given screenshots of UI below,

<img width="1260" alt="Screen Shot 2020-08-14 at 5 37 15 PM" src="https://user-images.githubusercontent.com/22999894/90294779-46d25f80-de55-11ea-95b3-f1e298aa0b29.png">

**Comment by hrishikeshpaul** [comment]
- Add support to select technologies, ASSAY types (28 in 1st portal release) and biomarker types.

**Comment by hrishikeshpaul** [comment]
- Add icons for +/- etc based on here: https://discovery.lifemapsc.com/gene-expression-signals

**Comment by emquardokus** [comment]
Gene--> transcribed to mRNA (messenger RNA)--> translated into Protein---> post-translational modifications are possible that can result in Proteoforms defined as products differing due to genetic variation, alternatively spliced RNA, transcripts, and post-translational modifications like phosphorylation, acetylation, N-linked glycosylation, amidation,  hydroxylation, methylation, O-linked glycosylation, ubiquitylation, pyrrolidone carboxylic acid, sulfation, palmitoylation, lipidation, proteolytic cleavage (like in the case of Pro-insulin to insulin), carbonylation...

**Comment by emquardokus** [comment]
CHALLENGE: Flow cytometry are proteins detected by use of antibodies that detect 1 specific protein---these are reported as +/- , dim/bright, high/low...this presents a challenge for reporter.  A cell type will be represented by both markers that are present AND absent---not just present like all other types of marker data sets.

**Comment by emquardokus** [comment]
Lipids are not encoded by genes: DOI:https://doi.org/10.1016/j.cell.2010.11.033
Metabolites also are not encoded by genes: https://en.wikipedia.org/wiki/Metabolome
Therefore represent a novel type of biomarker compared to genes (DNA)--> mRNA--> protein which are genetically encoded.
