### ISSUE TITLE
ASCT+B DB

### ISSUE THREAD

**Issue by hrishikeshpaul** [hubmapconsortium/ccf-asct-reporter#16]
The basic idea is to take the data from google sheets and create a database. But instead of taking the whole ASCT+B tables, the notion is to start off with biomarkers. 

As per our discussion, the tables will now include 6 columns of biomarkers (which is 1 right now). This is essentially make the table more complicated. With each anatomical structure having 2 columns and cells having 2 columns, for a sheet with 4 levels of AS, CT and B will have 14 columns (including the ontology links). Therefore, to overcome this complexity, creating a database would be beneficial. 

### Working

![asct](https://user-images.githubusercontent.com/22999894/91219630-ed85ee00-e6e8-11ea-9c69-ee9f972b2bc3.png)

The database could be a relational or non relational or a graph based database. Since we are only starting off the database with biomarkers only, we need to write a script to extract all the aliases of the current biomarkers that we have. 

This [API](https://www.genenames.org/help/rest/) can be used to retrieve the data of a particular biomarker. Although there is one limitation - only 10 requests can be made every second. 

Therefore, the script would have to accommodate this. Additionally, the script could always be running, and updating out database in the background, as the biomarker names are constantly going updates.

### Advantages
1. Have our own database of biomarkers names. This will drastically reduce wait time for retrieving biomarker names.
2. Editing, Inputting data will become much easier. 
3. Will reduce the complexity of the AST+B tables.

### Disadvantages
1. With any server feature, security is important. Will need to implement an extra layer of security so that only the authorized can edit the data.
2. May be opposed by experts that prefer working with google sheets, rather than a database.

### Questions
1. Is the data from genenames.org free to use? 
2. Should the user have the ability to make changes to the database for this version with the biomarkers?

**Comment by bherr2** [comment]
I would highly discourage having a server at all (I realize we added a server for google sheets, but that was because we had no choice).

Here is an alternative:

* We write scripts to periodically download and compile mapping resources as flat JSON files, saved in the repo, that can be loaded on the client side. Lookups then happen on the client side at blazing speeds.

* HGNC has an endpoint for downloading data as tab-separated data. [Custom Data interface](https://www.genenames.org/download/custom/) - [example data download](https://www.genenames.org/cgi-bin/download/custom?col=gd_hgnc_id&col=gd_app_sym&col=gd_app_name&col=gd_status&col=gd_prev_sym&col=gd_aliases&status=Approved&hgnc_dbtag=on&order_by=gd_hgnc_id&format=text&submit=submit) -- which you can see that its not that big of a file to begin with.

**Comment by bherr2** [comment]
Raw JSON data can also be downloaded via [ftp](ftp://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/json/). If using this, we'd probably want to strip out some of the data to keep just the data we need for matching/etc.

**Comment by hrishikeshpaul** [comment]
I think it would we great to have Ellen and Katy in this discussion. I'll put out a mail shortly notifying them.

**Comment by bherr2** [comment]
Ok. I sent you a message on slack
