### ISSUE TITLE
Playground Report Counts mismatch.

### ISSUE THREAD

**Issue by vutukuriajay2241** [hubmapconsortium/ccf-asct-reporter#248]
When data is inserted manually(In Table) vs. directly utilizing the URL of a Google-sheet(Upload), there is a mismatch in the counts.

**Comment by emquardokus** [comment]
@vutukuriajay2241 can you elaborate on this?  When you say "manually in table" do you mean in the current table? That template is actually OLD and should be replaced with the newest ASCT+B template we are using. That's probably why this isn't working right.  To be honest, I never use this feature, I DO use the upload either template or ASCT+B google sheet, both of those are using the most recent (since March 2021) template.
<img width="1083" alt="Screen Shot 2021-10-22 at 9 41 24 PM" src="https://user-images.githubusercontent.com/47257000/138537644-46a34e78-ec3e-485f-8c56-dca65036fa13.png">

**Comment by vutukuriajay2241** [comment]
The problem is When I use Upload feature the counts are not getting same as when we paste in the Table (The mismatch is  Body is counting as Unique AS when I paste in the Table option) thats the only problem
