### ISSUE TITLE
BUG: table version selection dialog Incorrect for some tables

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#276]
@bherr2 
Looked at version selection dialog tonight.

1) Blood, Blood vasculature are shown as only version 1.0---this is not correct.  It should be version 1.1

Blood and Bone marrow v 1.0 were together, but v1.1 we split them Blood and Bone Marrow

Vasculature v1.0 became Blood Vasculature v1.1  Same table, just better naming and ontology ID.

<img width="516" alt="Screen Shot 2021-11-17 at 12 01 10 AM" src="https://user-images.githubusercontent.com/47257000/142137979-fc759452-0dc5-4d76-9488-247d26a01e60.png">

2) The  list is NOT alphabetical order, it's all over the place...not sure what the sort is...
<img width="515" alt="Screen Shot 2021-11-17 at 12 07 24 AM" src="https://user-images.githubusercontent.com/47257000/142139129-80e837c4-6e0b-4e47-af22-5676713ecf8f.png">

3) I've mocked up what I think the dialog should include that it does not yet include. 

It should have an "All organs" like it used to have with the same v1.0 or 1.1 options. 
It should have titles of ograns and versions above this.  
I outlined in RED only to emphasize what I added, this should , of course be in black and properly aligned. 
<img width="570" alt="Screen Shot 2021-11-17 at 12 11 46 AM" src="https://user-images.githubusercontent.com/47257000/142139030-b54010ad-3838-4edf-8f40-4dab7666acc4.png">

**Comment by bherr2** [comment]
For #2, I think we just did it in order that it was configured. So you likely see the first 11 tables first, followed by the second 11 tables.. Agree it would make sense for it to be alphabetical.

For #3, what happens when you pick v1.1 but a table does not have a v1.1? Should we have an option called latest (to pick the most recent version)? And latest draft(?) -- some thought on this could go a long way. I agree that it could be useful.

**Comment by bherr2** [comment]
As part of this, I'd love to get the configuration out to a JSON file. It could be useful for other related projects because they can then 'query' for the available tables
