### ISSUE TITLE
Move new v1.2 tables out of DRAFT mode and into the main application

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-asct-reporter#438]
I need:
* A list of DRAFT tables to move out of DRAFT mode
* A list of published tables which did not change, but was included in v1.2
* A list of new DRAFT tables to replace the published DRAFT tables (I think we do this now, right?)

**Comment by emquardokus** [comment]
Checked in ASCT+B reporter 7-16-2022 what the status of this issue was: 
1. Correct tables had "draft" removed from name for CCF release v1.2 (3rd); 
2.Five (5) that remained in draft, unchanged and had been DOI'd in CCF release v1.1 were: 
heart, peripheral nervous system, prostate, ureter, urinary bladder. 
4. Those that remained in draft that were anticipated for release 3, but not filled were spinal cord and breast.
5. New table gid list is forthcoming for 4th release ASCT+B tables.

**Comment by emquardokus** [comment]
Attached spreadsheet containing new gid for CCF release v1.3 (release 4):
[7-16-2022_New_DRAFT_ASCT+B_Table_gid.xlsx](https://github.com/hubmapconsortium/ccf-asct-reporter/files/9127050/7-16-2022_New_DRAFT_ASCT%2BB_Table_gid.xlsx)

**Comment by bherr2** [comment]
DRAFT tables are now deployed
