### ISSUE TITLE
Detect OMAP formatted tables and convert to ASCT+B tables on the fly

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-asct-reporter#611]
When a user uploads an OMAP (either CSV or Google Sheet), exactly like they would an ASCT+B table, convert the OMAP to an ASCT+B table and parse normally as an ASCT+B table.

Examples of OMAPs are here: https://humanatlas.io/omap

If you have questions about OMAPs, please consult with Ellen ( @emquardokus  ).

**Comment by emquardokus** [comment]
@bherr2 currently only two fields in an OMAP are equivalent to supported fields in an ASCT+B table.

**Comment by emquardokus** [comment]
@bherr2 Related: https://github.com/hubmapconsortium/ccf-asct-reporter/pull/412 that Sai Ajay Vutukuri had done which was an interesting potential method, except OMAPs no longer contain the "antibody name" field because the experts deemed it non-standard format.  We have catalog  number ,  vendor and RRID which can be validated and other information pulled from Charles Kollar is using this for RRID validation, but those other fields exist too:
https://scicrunch.org/resolver/RRID:AB_2909618.json

**Comment by bherr2** [comment]
@pbrm4 @emquardokus we need to have a meeting to finalize how to convert OMAPs to ASCT+B format

**Comment by bherr2** [comment]
SOP: How to use ASCT+B Reporter to Construct new OMAPs https://docs.google.com/document/d/1fVh5SNH00Vs8Ik9kzndnNW7q2tzi_n-crQfMey0HGHc/edit#heading=h.lpsf90jpnlzf
